# Generated by Django 5.1.1 on 2024-10-07 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Имя')),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_card', models.CharField(max_length=254, unique=True, verbose_name='ID карточки')),
                ('election', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='election_others', to='main.electionmodel', verbose_name='Голосования')),
            ],
        ),
    ]
