# Generated by Django 5.1.1 on 2024-10-10 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('choice', '0001_initial'),
        ('election', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_card', models.CharField(max_length=254, unique=True, verbose_name='ID карточки')),
                ('choice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='choice.choicemodel', verbose_name='Выборы ответов')),
                ('election', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='election.electionmodel', verbose_name='Голосования')),
            ],
        ),
    ]
