# Generated by Django 5.1.1 on 2024-10-07 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, unique=True, verbose_name='Имя выбора')),
                ('election_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='elections', to='main.electionmodel', verbose_name='Голосования')),
            ],
        ),
        migrations.AddField(
            model_name='usermodel',
            name='choice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='choice_model', to='main.choicemodel', verbose_name='Выборы ответов'),
        ),
    ]
