# Generated by Django 5.1.1 on 2024-10-07 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_choicemodel_usermodel_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choicemodel',
            name='election_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='choices', to='main.electionmodel', verbose_name='Голосования'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='election',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user', to='main.electionmodel', verbose_name='Голосования'),
        ),
    ]
