# Generated by Django 5.1.1 on 2024-10-07 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_choicemodel_election_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='choice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user', to='main.choicemodel', verbose_name='Выборы ответов'),
        ),
    ]
