# Generated by Django 5.1.1 on 2024-10-07 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_usermodel_choice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choicemodel',
            old_name='election_id',
            new_name='election',
        ),
    ]
