# Generated by Django 5.1.1 on 2024-10-08 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_election_id_choicemodel_election'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choicemodel',
            name='election',
        ),
        migrations.AddField(
            model_name='electionmodel',
            name='choices',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='choices', to='main.choicemodel', verbose_name='Голосования'),
        ),
    ]
