# Generated by Django 5.1.1 on 2024-10-08 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_choicemodel_election_electionmodel_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electionmodel',
            name='choices',
        ),
        migrations.AddField(
            model_name='choicemodel',
            name='election',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='choices', to='main.electionmodel', verbose_name='Голосования'),
        ),
    ]
