# Generated by Django 5.1.1 on 2024-10-08 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_electionmodel_choices_choicemodel_election'),
    ]

    operations = [
        migrations.AddField(
            model_name='electionmodel',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Время создания'),
        ),
    ]
