# Generated by Django 5.1.1 on 2025-01-16 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('election', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, unique=True, verbose_name='Имя выбора')),
                ('election', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='election.electionmodel', verbose_name='Голосования')),
            ],
        ),
    ]
