name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: docker compose up -d --build

      - name: Wait for services to become healthy
        run: |
          echo "Waiting for services..."
          sleep 15
          docker compose ps

      -  name: Run tests
         run: docker compose exec -T api env TEST=1 ./entrypoint.sh

      - name: Tear down
        if: always()
        run: docker compose down --volumes